# Generated by Django 4.1.3 on 2023-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomexApp', '0002_auto_20220828_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
