# Generated by Django 2.2.15 on 2022-09-04 14:36

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('Thumbnail', models.ImageField(default=product.models.default_thumb_path, upload_to=product.models.get_collection_image_filepath)),
                ('description', models.TextField(default='No description for this Collection!')),
                ('start_date', models.DateField(default='September 04, 2022')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=225)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=200)),
                ('collection', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0, max_length=6)),
                ('Availability', models.BooleanField(default=True)),
                ('Description', models.TextField(default='No Description for this Items')),
            ],
        ),
        migrations.CreateModel(
            name='Product_size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_size', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to=product.models.get_product_image_filepath)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('products', models.ManyToManyField(to='product.Products')),
            ],
        ),
    ]
