# Generated by Django 2.2.15 on 2022-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='start_date',
            field=models.CharField(default='September 04, 2022', max_length=255),
        ),
    ]
