# Generated by Django 2.2.15 on 2022-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220904_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='start_date',
            field=models.CharField(default='September 05, 2022', max_length=255),
        ),
    ]
