# Generated by Django 2.2.15 on 2022-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220905_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='start_date',
            field=models.CharField(default='September 07, 2022', max_length=255),
        ),
    ]
