# Generated by Django 4.1.3 on 2023-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220907_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='start_date',
            field=models.CharField(default='October 15, 2023', max_length=255),
        ),
    ]
