# Generated by Django 2.2.15 on 2022-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
