# Generated by Django 2.2.15 on 2022-09-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_info_order_listorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listorders',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='listorders',
            name='date',
            field=models.CharField(default='09/07/2022, 01:39:18', max_length=255),
        ),
    ]
